### ISSUE TITLE
Question: How to find flushed data

### ISSUE THREAD

**Issue by bayreporta** [documentcloud/pixel-ping#11]
Hey all, 

Sorry I'm new to this find of stuff, but I successfully got pixel-ping working on our server, and when I run it it appears to successfully flush based on the messages, but I cant find any new files or anything like that. I'm working off the DocCloud explanation of how to use this, so the endpoint is mydomain/save_hits. I'm using 9187 port as well.

Any help on this would be greatly appreciated. Thanks in advance.

**Comment by jashkenas** [comment]
Howdy!

If everything is still working the way I remember — Pixel Ping shouldn't be writing any new files or anything like that. It merely flushes the hits, at the interval (in seconds) that you have configured, to the endpoint you've configured, as a simple JSON POST request.

So your server should be getting the requests, unless for some reason Pixel Ping can't communicate successfully.

Full source code available here: https://documentcloud.github.io/pixel-ping/docs/pixel-ping.html

**Comment by bayreporta** [comment]
Ok thanks!
